export const countryOptions = [
  { value: "ireland", label: "Ireland" },
  { value: "afghanistan", label: "Afghanistan" },
  { value: "argentina", label: "Argentina" },
  { value: "australia", label: "Australia" },
  { value: "brazil", label: "Brazil" },
  { value: "canada", label: "Canada" },
  { value: "china", label: "China" },
  { value: "denmark", label: "Denmark" },
  { value: "egypt", label: "Egypt" },
  { value: "france", label: "France" },
  { value: "germany", label: "Germany" },
  { value: "greece", label: "Greece" },
  { value: "hungary", label: "Hungary" },
  { value: "india", label: "India" },
  { value: "japan", label: "Japan" },
  { value: "kenya", label: "Kenya" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "malaysia", label: "Malaysia" },
  { value: "netherlands", label: "Netherlands" },
  { value: "oman", label: "Oman" },
  { value: "peru", label: "Peru" },
  { value: "qatar", label: "Qatar" },
  { value: "russia", label: "Russia" },
  { value: "spain", label: "Spain" },
  { value: "thailand", label: "Thailand" },
  { value: "united_kingdom", label: "United Kingdom" },
  { value: "united_states", label: "United States" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },
  { value: "zimbabwe", label: "Zimbabwe" },
];
